{ DEBUG_NONE, "No debugging"},
{ DEBUG_ERRS, "Verbose error reporting"},
{ DEBUG_INIT, "Debug initialization"},
{ DEBUG_SOCKETS, "Debug socket operations"},
{ DEBUG_SPIFFY, "Debug the spiffy sending code"},
{ DEBUG_LEECHER, "Debug leecher"},
{ DEBUG_LEECHER_RELIABLE, "Debug leecher reliability"},
{ DEBUG_LEECHER_ALL, "Debug leecher (all)"},
{ DEBUG_SEEDER, "Debug seeder"},
{ DEBUG_SEEDER_RELIABLE, "Debug seeder reliability"},
{ DEBUG_SEEDER_ALL, "Debug seeder (all)"},
{ DEBUG_CMD_GET, "Debug GET commands"},
